import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const beyonders = localFont({
  src: "../public/fonts/Beyonders.ttf",
  variable: "--font-beyonders",
});

const coolvetica = localFont({
  src: "../public/fonts/Coolvetica.otf",
  variable: "--font-coolvetica",
});

const nature = localFont({
  src: "../public/fonts/Nature.ttf",
  variable: "--font-nature",
})

const natureLight = localFont({
  src: "../public/fonts/Nature-Light.ttf",
  variable: "--font-nature-light",
})

export const metadata: Metadata = {
  title: "Mojo: Habit & Task Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${beyonders.variable} ${coolvetica.variable} ${nature.variable} ${natureLight.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}